#first_name=input()
#last_name=input()
#print(last_name + " " + first_name)
name="maximum protection"
print(name)
print(name[3:])
print(name[:17])
print(name[2:6])
print(name[:-5])
print(name[-3:])
print(name[8:])
#print(name[3:5])
#print(name[3:5])
#print(name[3:5])
#print(name[3:5])
#print(name[3:5])
print(name.capitalize())
print(len(name))
print(name.lower())
print("*************")
print(name.upper())
print(name.index("x"))
#print(type(name.split()))
list1=name.split()
list2=name.replace("maximum","tooth")
print(list1)
print(list2)
